config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :admins
  
  # devise_scope :employee do
  #   root to: "devise/sessions#new"
  # end
  
  root to: "home#dashboard"
  
  authenticated :admin do
    root "home#dashboard", as: :admin_dashboard
  end
  
  authenticated :employee do
    root "home#dashboard", as: :employee_dashboard
  end
  
  get 'dashboard', to: 'home#dashboard',as: :dashboard
  resources :jobs, except:[:index] do
    
    get 'assign_clients', to: 'jobs#assign_clients',as: :assign_clients
    get 'assign_employees', to: 'jobs#assign_employees',as: :assign_employees
  end
  resources :tasks , except:[:index] do
    get 'assign', to: 'tasks#assign',as: :assign
    get 'status', to: 'tasks#status',as: :status
  end
  
  resources :admins , except:[:index]
  resources :employees , except:[:index]
  resources :clients, except:[:index]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def name
    firstname + " " + lastname
  end
  
  has_many :employee_jobs, :dependent => :destroy
  has_many :tasks, as: :owner
  
  has_many :task_assigned, :as => :assignee, :dependent => :destroy
  
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  # has_many :tasks, as: :assignee
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    
    before_action :set_employee, only: [:show, :edit, :update, :destroy]

    
    def index
      authorize Employee
      @employees = Employee.all
    end
    
    def show
      authorize @employee
    end
    
    def edit
      authorize @employee
    end
    
    def new
      # byebug
      authorize Employee
      @employee = Employee.new
    end
    
    def create
      authorize Employee
      @employee = Employee.new(employee_params)

        respond_to do |format|
          if @employee.save
            format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
            format.json { render :show, status: :created, location: @employee }
          else
            format.html { render :new }
            format.json { render json: @employee.errors, status: :unprocessable_entity }
          end
        end
    end

  def update
    authorize @employee
    
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @employee
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 
  
  private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:picture,:firstname,:lastname,:username,:phone,:email,:pay,:dob,:address,:password,:password_confirmation,:current_password)
    end    
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
    <%= bootstrap_form_for(@employee) do |f| %>
        <%= f.text_field :firstname %>
        <%= f.text_field :lastname %>
        <%= f.date_field :dob %>
        <%= f.number_field :pay %>
        <%= f.text_field :username %>
        <%= f.text_field :email %>
        <%= f.text_field :phone %>
        <%= f.text_field :address %>
        <%= f.file_field :picture %>
        
        <% if (not(@employee.nil? and current_employee.nil? )) and  (current_employee == @employee) %>
          <%= f.password_field :current_password, autocomplete: "off" %>
        <% else %>
          <%= f.password_field :password %>
          <%= f.password_field :password_confirmation %>
        <% end %>
        <%= f.submit "Submit",class:"btn btn-info" %>
      
    <% end %>
  

app/views/employees/edit.html.erb
<div class="container">
    <div class="col-md-offset-4 col-md-5 well job_sign_up">
        <center><h2>Edit Employee Information</h2></center>
        <%= render 'form' %>
    </div>
</div>

app/views/employees/index.html.erb
<%= link_to 'Create New Employee', new_employee_path ,class:"col-md-offset-0 col-md-3 col-xs-offset-3 col-xs-7 btn btn-info btn_uper_set" %>
  <br>
  <br>
<div class="table-responsive">
  
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>FirstName</th>
        <th>Lastname</th>
        <th>Username</th>
        <th>Email</th>
        <th class="center">Show</th>
        <th class="center">Edit</th>
        <th class="center">Destroy</th>
        <!--<th>Notes</th>-->
        <!--<th>Total Time</th>-->
      </tr>
    </thead>
    <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstname %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.username %></td>
        <td><%= employee.email %></td>
        
        <td><%= link_to '', employee_path(employee),class:"fa fa-eye btn btn-default btn-sm" %></td>
        <td><%= link_to '', edit_employee_path(employee),class:"fa fa-pencil btn btn-info btn-sm" %></td>
        <td><%= link_to '',employee, method: :delete, data: { confirm: 'Are you sure?' },class:"fa fa-trash-o btn btn-danger btn-sm" %></td>
        
      </tr>
    <% end %>
    
</table>
</div>

app/views/employees/new.html.erb
<div class="container">
    <div class="col-md-offset-4 col-md-5 well job_sign_up">
        <center><h2>Create New Employee</h2></center>
        <%= render 'form' %>
    </div>
</div>

app/views/employees/show.html.erb
<div class="container">

  <div class="col-md-offset-3 col-md-6 well" style="background-color:white">
  <h4 class="center">Employee Details</h4>
  <table style="width:100%" class="table table-bordered">
    
    
    <tr>
      <th class="center">Picture</th>
      <td><%= image_tag @employee.picture.url(:medium) %></td>
    </tr>
    
    <tr>
      <th class="center">FirstName</th>
      <td><%= @employee.firstname %></td>
    </tr>
    <tr>
      <th class="center">Lastname</th>
      <td><%= @employee.lastname %></td>
    </tr>
    <tr>
      <th class="center">Username</th>
      <td><%= @employee.username %></td>
    </tr>
    
    <tr>
      <th class="center">Phone</th>
      <td><%= @employee.phone %></td>
    </tr>
    <tr>
      <th class="center">Email</th>
      <td><%= @employee.email %></td>
    </tr>
    
    <tr>
      <th class="center">Pay</th>
      <td><%= @employee.pay %></td>
    </tr>
    <tr>
      <th class="center">Date of birth</th>
      <td><%= @employee.dob %></td>
    </tr>
    <tr>
      <th class="center">Address</th>
      <td><%= @employee.address %></td>
    </tr>
    
    
  </table>
  
  <%= policy(@employee).edit? ? (link_to 'Edit Employee',edit_employee_path(@employee),class:"col-md-offset-4 col-md-4 col-xs-offset-4 col-xs-4 btn btn-info"):nil %><br><br>
  </div>

</div>