config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :admins
  
  # devise_scope :employee do
  #   root to: "devise/sessions#new"
  # end
  
  root to: "home#dashboard"
  
  authenticated :admin do
    root "home#dashboard", as: :admin_dashboard
  end
  
  authenticated :employee do
    root "home#dashboard", as: :employee_dashboard
  end
  
  get 'dashboard', to: 'home#dashboard',as: :dashboard
  resources :jobs, except:[:index] do
    
    get 'assign_clients', to: 'jobs#assign_clients',as: :assign_clients
    get 'assign_employees', to: 'jobs#assign_employees',as: :assign_employees
  end
  resources :tasks , except:[:index] do
    get 'assign', to: 'tasks#assign',as: :assign
    get 'status', to: 'tasks#status',as: :status
  end
  
  resources :admins , except:[:index]
  resources :employees , except:[:index]
  resources :clients, except:[:index]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
    enum status: [:in_progress,:complete]
    has_many :employee_jobs, :dependent => :destroy
    has_many :tasks, :dependent => :destroy
    
    has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
    
    
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :set_job, only: [:show, :edit, :update, :destroy]
    # before_action :authenticate_admin!
    # 	load_and_authorize_resource

    
    def index
      authorize Job
      @jobs = Job.all
    end
    
    def assign_clients
      authorize Job
      @job = Job.find(params[:job_id])
      # byebug
      clients_to_be_assigned = params[:clientjob][:client_ids]
      # check_all_created
      clients_to_be_assigned.each do |client|
        if(client.present? and @job)
          Clientjob.create!(client_id: client,job_id:@job.id)
        end
      end
      
      redirect_to @job
    end
    
    def assign_employees
      authorize Job
      @job = Job.find(params[:job_id])
      # byebug
      employees_to_be_assigned = params[:clientjob][:employee_ids]
      # check_all_created
      employees_to_be_assigned.each do |employee|
        if(employee.present? and @job)
          EmployeeJob.create!(employee_id: employee,job_id:@job.id)
        end
      end
      
      redirect_to @job
    end
    
    def show
      authorize @job
      clients = Clientjob.where(job_id: @job.id).pluck(:client_id)
      @tasks = @job.tasks
      @all_unassigned_client = Client.where.not(id: clients)
      @all_assigned_clients = Client.joins(:clientjobs).where('clientjobs.job_id' => @job.id)
      
      employees =  EmployeeJob.where(job_id: @job.id).pluck(:employee_id)
      @all_unassigned_employees = Employee.where.not(id: employees)
      @all_assigned_employees = Employee.joins(:employee_jobs).where('employee_jobs.job_id' => @job.id)
      
      # byebug
      
      
    end
    
    def edit
      authorize @job
    end
    
    def new
      authorize Job
      @job = Job.new
    end
    
    def create
      authorize Job
      @job = Job.new(job_params)

        respond_to do |format|
          if @job.save
            format.html { redirect_to @job, notice: 'job was successfully created.' }
            format.json { render :show, status: :created, location: @job }
          else
            format.html { render :new }
            format.json { render json: @job.errors, status: :unprocessable_entity }
          end
        end
  end

  def update
    authorize @job
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @job
    @job.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 
  
  private

    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:picture,:name,:contact,:due_date,:status,:comment,:notes,:total_time)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_assignee_list.html.erb
<table class="table table-bordered">
  <thead>
    <th>
      Assigned
    </th>
    <!--<th class="center">Actions</th>-->
  </thead>
  <tbody>
    <% list.each do |element| %>
    <tr>
      <td> <%= element.name %> </td>
      <!--<td class="center"> <= link_to 'Remove', '#',class:"fa fa-trash-o btn btn-danger btn-sm" %> </td>-->
    </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/_form.html.erb
    <%= bootstrap_form_for(@job) do |f| %>
    
        <%= f.text_field :name %>
          
      <%= f.text_field :contact %>
      <%= f.date_field :due_date %>
      <%#= f.number_field :status %>
      
      <%= f.select :status, Job.statuses.map { |key, value| [key.humanize, key] } %>
      
      <%= f.text_field :comment %>
      <%= f.text_area :notes %>
      <%= f.number_field :total_time %>
      <%= f.file_field :picture %>
      <%= f.submit "Submit",class:"btn btn-info" %>
      
    <% end %>
  

app/views/jobs/_job.html.erb
            <tr>
              <td><%= job.name %></td>
              <td><%= job.contact %></td>
              <td><%= job.due_date %></td>
              <td><%= job.status %></td>
              <td><%= job.comment %></td>
              <td><%= job.notes %></td>
              <td><%= job.total_time %></td>
              <td class="center"><%= link_to '', job_path(job),class:"fa fa-eye btn btn-default btn-sm" %></td>
              
              <% if policy(Job).edit? %>
              	<td class="center"><%= link_to '', edit_job_path(job),class:"fa fa-pencil btn btn-info btn-sm" %></td>
              <% end %>
              <% if policy(job).destroy? %>
                <td class="center"><%= link_to '',job, method: :delete, data: { confirm: 'Are you sure?' },class:"fa fa-trash-o btn btn-danger btn-sm" %></td>
              <% end %>
              
              
              
              
              
            </tr>

app/views/jobs/edit.html.erb
<div class="container">
    <div class="col-md-offset-4 col-md-5 well job_sign_up">
        <center><h2>Edit Job Information</h2></center>
        <%= render 'form' %>
    </div>
</div>

app/views/jobs/index.html.erb
<!--<div class="container" style="margin-bottom: 300px;">-->
<!--  <div class="row">-->
  <!-- <div class="col-md-3">-->
			<!--<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">-->

				<!--<h4 class="heading-primary"><strong>Filter</strong> By</h4>-->
    <!--    <nav>-->
    <!--  <ul class="nav nav-pills nav-stacked" >-->
    <!--    <li class="active"><a href="#section1">Section 1</a></li>-->
    <!--    <li><a href="#section2">Section 2</a></li>-->
    <!--    <li><a href="#section3">Section 3</a></li>-->
    <!--  </ul>-->
    <!--</nav>-->
				
        
  <!--    <ul class="nav nav-pills nav-stacked" >-->
  <!--      <li class="active"><a href="#section1">Section 1</a></li>-->
  <!--      <li><a href="#section2">Section 2</a></li>-->
  <!--      <li><a href="#section3">Section 3</a></li>-->
  <!--      <li><a href="#section2">Section 4</a></li>-->
        
  <!--      <br>-->
  <!--      <br>-->
  <!--    </ul>-->
   
      
			<!--</aside>-->
		<!--</div>-->
		
    <div class="table-responsive">
      
      <%# if policy(@post).update? %>
  <%#= link_to "Edit post", edit_post_path(@post) %>
<%# end %>
      
      <%= policy(Job).new? ? (link_to 'Create New Job', new_job_path,class:"col-md-offset-0 col-md-3  col-xs-8 btn btn-info btn_uper_set") : nil %> <br><br>
      <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Contact</th>
              <th>Due Date</th>
              <th>Status</th>
              <th>Comment</th>
              <th>Notes</th>
              <th>Total Time</th>
              <th class="center">Show</th>
              <th class="center">Edit</th>
              <th class="center">Destroy</th>
            </tr>
          </thead>
          <tbody>
          <% @jobs.each do |job| %>
            <tr>
              <td><%= job.name %></td>
              <td><%= job.contact %></td>
              <td><%= job.due_date %></td>
              <td><%= job.status %></td>
              <td><%= job.comment %></td>
              <td><%= job.notes %></td>
              <td><%= job.total_time %></td>
              <td><%= link_to ' Show', job_path(job),class:"fa fa-eye btn btn-default btn-sm" %></td>
              <td><%= link_to ' Edit', edit_job_path(job),class:"fa fa-pencil btn btn-info btn-sm" %></td>
              <td><%= link_to ' Destroy',job, method: :delete, data: { confirm: 'Are you sure?' },class:"fa fa-trash-o btn btn-danger btn-sm" %></td>
              
            </tr>
          <% end %>
          
      </table>
      <!--<= link_to 'Create New Job', new_job_path %>-->
     
</div>
</div>
<br>
<br>

app/views/jobs/new.html.erb
<div class="container">
    <div class="col-md-offset-4 col-md-5 well job_sign_up">
        <center><h2>Create New Job</h2></center>
        <%= render 'form' %>
    </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <h2 class="center"><%= @job.name %> Details</h2>
  <div class="col-md-12 bus-adm">
	        	<center>
            <div class="tabs tabs-bottom tabs-simple">
          		<ul class="nav nav-tabs">
          			<li class="active">
          				<a href="#Pending" data-toggle="tab">Job</a>
          			</li>
          			<li>
          				<a href="#approved" data-toggle="tab">Clients</span></a>
          			</li>
          			<li>
          				<a href="#rejected" data-toggle="tab">Employees</span></a>
          			</li>
          			<li>
          				<a href="#job_tasks" data-toggle="tab">Job Tasks</span></a>
          			</li>
          		</ul>
            </div>
            </center>

            	<div class="row">
            	    <div class="col-md-12">
                    	<div class="tab-content e-tabs">
                    	    <div class="tab-pane active" id="Pending">
                    	      <div class="row">
    
     
                          	   <div class="col-md-12">
                                  <table style="width:100%" class="table table-bordered">
                                    
                                    <tr>
                                      <th class="center">Picture</th>
                                      <td><%= image_tag @job.picture.url(:medium) %></td>
                                    </tr>
                                    
                                    
                                    <tr>
                                      <th>Name:</th>
                                      <td><%= @job.name %></td>
                                    </tr>
                                    <tr>
                                      <th>Contact</th>
                                      <td><%= @job.contact %></td>
                                    </tr>
                                    <tr>
                                      <th>Due Date:</th>
                                      <td><%= @job.due_date %></td>
                                    </tr>
                                    
                                    <tr>
                                      <th>Status</th>
                                      <td><%= @job.status.humanize %></td>
                                    </tr>
                                    <tr>
                                      <th>Comment</th>
                                      <td><%= @job.comment %></td>
                                    </tr>
                                    <tr>
                                      
                                      <th>Notes</th>
                                      <td><%= @job.notes %></td>
                                    </tr>
                                    
                                    <tr>
                                      <th>Total Time</th>
                                      <td><%= @job.total_time %></td>
                                    </tr>
                                    
                                  </table>
                                  <% if policy(@job).edit? %>
                                    <%= link_to 'Edit Job',edit_job_path(@job),class:"col-md-offset-4 col-md-4 col-xs-offset-4 col-xs-4 btn btn-info" %>
                                  <% end %>
                              </div>
                            </div>
                    	    </div>
                    	    <div class="tab-pane" id="approved">
                    	      <% if admin_signed_in? %>
                              <h2 class="center">Clients For This Job</h2>
                              <div class="row">
                              
                                <div class="col-md-6">
                                  <%= form_tag job_assign_clients_path(@job), :method => :get do %>
                                    <table class="table table-bordered">
                                    <thead>
                                      <th>Not Assigned</th>
                                      <th>Action</th>
                                    </thead>
                                    
                                    <tbody>
                                      
                                      <%= collection_check_boxes("clientjob", :client_ids, @all_unassigned_client, :id, :name) do |b| %>
                                        <tr>
                                          <td><%= b.label %></td>
                                          <td><%= b.check_box %></td>
                                          
                                        </tr>
                                      <% end %>
                                        
                                    </tbody>
                              
                                  </table>
                                  <%= submit_tag 'Assign',class:"col-md-offset-0 col-md-4 col-xs-offset-4 col-xs-4 btn btn-info manage_btn" %>
                                <% end %>
                                </div>
                                <div class="col-md-6">
                                  <%= render partial:'assignee_list', locals: { list: @all_assigned_clients} %>
                                </div>
                              </div>
                    	    </div>
                    	    <div class="tab-pane" id="rejected">
                    	        <h2 class="center">Employees For This Job</h2>
                                <div class="row">
                                  <div class="col-md-6">
                                    <%= form_tag job_assign_employees_path(@job), :method => :get do %>
                                      <table class="table table-bordered">
                                      <thead>
                                        <!--<th>Not Assigned</th>-->
                                        <th>Not Assigned</th>
                                        <th>Action</th>
                                      </thead>
                                      
                                      <tbody>
                                        
                                        <%= collection_check_boxes("clientjob", :employee_ids, @all_unassigned_employees, :id, :name) do |b| %>
                                          <tr>
                                            <td><%= b.label %></td>
                                            <td>
                                            
                                              <%= b.check_box  %>
                                            </td>
                                            <!--<td><label for="default" class="btn btn-default">-->
                                            <!--<input type="checkbox" id="default" class="badgebox">-->
                                            <!--<span class="badge">&check;</span></label></td>-->
                                          </tr>
                                        <% end %>
                                          
                                      </tbody>
                                
                                    </table>
                                    <%= submit_tag 'Assign',class:"col-md-offset-0 col-md-4 col-xs-offset-4 col-xs-4 btn btn-info manage_btn" %>
                                  <% end %>
                                  </div>
                                   <div class="col-md-6">
                                    <%= render partial:'assignee_list', locals: { list: @all_assigned_employees} %>
                                  </div>
                                  
                                </div>
                              <% end %>
                    	    </div>
                    	    <div class="tab-pane" id="job_tasks">
                    	      <%= link_to 'Add New Task' , new_task_path,class:"col-md-3 btn btn-info" %>
                    	      <%= render file:'tasks/index' %>
                    	    </div>
                    	</div>
            	    </div>
            	 </div>
            	    
            </div>
</div>