config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :admins
  
  # devise_scope :employee do
  #   root to: "devise/sessions#new"
  # end
  
  root to: "home#dashboard"
  
  authenticated :admin do
    root "home#dashboard", as: :admin_dashboard
  end
  
  authenticated :employee do
    root "home#dashboard", as: :employee_dashboard
  end
  
  get 'dashboard', to: 'home#dashboard',as: :dashboard
  resources :jobs, except:[:index] do
    
    get 'assign_clients', to: 'jobs#assign_clients',as: :assign_clients
    get 'assign_employees', to: 'jobs#assign_employees',as: :assign_employees
  end
  resources :tasks , except:[:index] do
    get 'assign', to: 'tasks#assign',as: :assign
    get 'status', to: 'tasks#status',as: :status
  end
  
  resources :admins , except:[:index]
  resources :employees , except:[:index]
  resources :clients, except:[:index]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!--<footer id="footer">-->
<!--	<div class="container">-->
<!--		<div class="row">-->
			<!--<div class="footer-ribbon">-->
			<!--	<span>Get in Touch</span>-->
			<!--</div>-->
<!--			<div class="col-md-3">-->
<!--				<div class="newsletter">-->
<!--					<h4>Newsletter</h4>-->
<!--					<p>Keep up on our always evolving product features and technology. Enter your e-mail and subscribe to our newsletter.</p>-->

<!--					<div class="alert alert-success hidden" id="newsletterSuccess">-->
<!--						<strong>Success!</strong> You've been added to our email list.-->
<!--					</div>-->

<!--					<div class="alert alert-danger hidden" id="newsletterError"></div>-->

<!--					<form id="newsletterForm" action="php/newsletter-subscribe.php" method="POST">-->
<!--						<div class="input-group">-->
<!--							<input class="form-control" placeholder="Email Address" name="newsletterEmail" id="newsletterEmail" type="text">-->
<!--							<span class="input-group-btn">-->
<!--								<button class="btn btn-default" type="submit">Go!</button>-->
<!--							</span>-->
<!--						</div>-->
<!--					</form>-->
<!--				</div>-->
<!--			</div>-->
<!--			<div class="col-md-3">-->
<!--				<h4>Latest Tweets</h4>-->
<!--				<div id="tweet" class="twitter" data-plugin-tweets data-plugin-options="{'username': '', 'count': 2}">-->
<!--					<p>Please wait...</p>-->
<!--				</div>-->
<!--			</div>-->
<!--			<div class="col-md-4">-->
<!--				<div class="contact-details">-->
<!--					<h4>Contact Us</h4>-->
<!--					<ul class="contact">-->
<!--						<li><p><i class="fa fa-map-marker"></i> <strong>Address:</strong> 1234 Street Name, City Name, United States</p></li>-->
<!--						<li><p><i class="fa fa-phone"></i> <strong>Phone:</strong> (123) 456-789</p></li>-->
<!--						<li><p><i class="fa fa-envelope"></i> <strong>Email:</strong> <a href="mailto:mail@example.com">mail@example.com</a></p></li>-->
<!--					</ul>-->
<!--				</div>-->
<!--			</div>-->
<!--			<div class="col-md-2">-->
<!--				<h4>Follow Us</h4>-->
<!--				<ul class="social-icons">-->
<!--					<li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>-->
<!--					<li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>-->
<!--					<li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>-->
<!--				</ul>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--	<div class="footer-copyright">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
				<!--<div class="col-md-1">-->
				<!--	<a href="index.html" class="logo">-->
				<!--		<img alt="Porto Website Template" class="img-responsive" src="img/logo-footer.png">-->
				<!--	</a>-->
				<!--</div>-->
<!--				<div class="col-md-12">-->
<!--					<center><p>© Copyright 2017. All Rights Reserved.</p></center>-->
<!--				</div>-->
				<!--<div class="col-md-4">-->
				<!--	<nav id="sub-menu">-->
				<!--		<ul>-->
				<!--			<li><a href="page-faq.html">FAQ's</a></li>-->
				<!--			<li><a href="sitemap.html">Sitemap</a></li>-->
				<!--			<li><a href="contact-us.html">Contact</a></li>-->
				<!--		</ul>-->
				<!--	</nav>-->
				<!--</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</footer>-->
<footer id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
			<center>
				<span>Powered By <a href="http://www.systemplus.com.pk/" target="_blank"> Systemplus</a>.</span>
			</center>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<!--<nav class="navbar navbar-default">-->
<!--  <div class="container-fluid">-->
<!--    <div class="navbar-header">-->
<!--      <a class="navbar-brand" href="#">WebSiteName</a>-->
<!--    </div>-->
<!--    <ul class="nav navbar-nav">-->
      <!--<li class="active"><a href="#">Home</a></li>-->
      
      
<!--      <li><a href="#">Page 1</a></li>-->
<!--      <li><a href="#">Page 2</a></li>-->
<!--      <li><a href="#">Page 3</a></li>-->
<!--    </ul>-->
<!--  </div>-->
<!--</nav>-->
<header id="header" >
<div class="header-body">
<div class="header-container container">
	<div class="header-row">
		<div class="header-column">
			<div class="header-logo">
				<a href="/">
					<img alt="Porto" width="200" height="100" data-sticky-width="82" data-sticky-height="40" data-sticky-top="33" src="/G_G_171220090757.jpeg">
				</a>
			</div>
		</div>
		<div class="header-column">
			
			<div class="header-row">
				<div class="header-nav">
					<button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main">
						<i class="fa fa-bars"></i>
					</button>
					
					<div class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1 collapse">
						<nav>
							<ul class="nav nav-pills" id="mainNav">
								<!--<li class="dropdown active">-->
								<!--	<a  href="index.html">-->
								<!--		Home-->
								<!--	</a>-->
								
								<!--</li>-->
								<% if (not admin_signed_in? and  not employee_signed_in?) %>
								<li class="">
									<a href="/admins/sign_in">
										Admin Login
									</a>
								</li>
								
								<li class="">
									<a  href="/employees/sign_in">
										Employee Login
									</a>
								
								
								</li>
								<% elsif admin_signed_in? %>
									
									
									<li class="">
									<a  href="<%= admin_dashboard_path %>">
										Admin Dashboard
									</a>
									</li>
									
									<li class="">
									<a  href="<%= admin_path(current_admin) %>">
										Profile
									</a>
									</li>
									
									<li class="">
									<a  href="<%= destroy_admin_session_path %>" data-method="delete">
										Log Out
									</a>
									</li>
								<% elsif employee_signed_in? %>
									
									
									<li class="">
									<a  href="<%= employee_dashboard_path %>">
										Employee Dashboard
									</a>
									</li>
									
									<li class="">
									<a  href="<%= employee_path(current_employee) %>">
										Profile
									</a>
									</li>
									
									<li class="">
									<a  href="<%= destroy_employee_session_path %>" data-method="delete">
										Log Out
									</a>
									</li>
									
								<% end %>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <meta name = "viewport" content = "width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
        <%#= notice %>
        <%#= alert %>
      
      <% if alert || notice %>
      <div class="alert alert-info" id="hide_notice_div">
          <strong>Info!</strong> <%= notice || alert %>
      </div>
    <% end %>
      <div style="margin-top: 50px;">
   
        <%= yield %>
      
      </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>